<!DOCTYPE html>
<html lang="en"><head>
<script src="presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="presentation_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Strategic Analysis Group">
  <title>MIB Cars Analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link rel="stylesheet" href="styles.css">
  <link href="presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">MIB Cars Analysis</h1>
  <p class="subtitle">Commercial prioritization and forecasting from sales opportunity data</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Strategic Analysis Group 
</div>
</div>
</div>

</section>
<section id="executive-summary" class="slide level2">
<h2>Executive Summary</h2>
<ul>
<li>This analysis examines an auto-parts sales opportunity pipeline, identifying structural inefficiencies (i.e.&nbsp;CRM input errors, lack of prioritization, and inaccurate forecasting) that drive a structurally low 22.7% conversion rate.</li>
<li>We propose two <strong>static / at-creation</strong> models: a win/loss classifier (<strong>AUROC 73.6%</strong>) for early opportunity prioritization, and a regression model for deal sizing with <strong>63.0% MdAPE</strong> on held-out test data.</li>
<li>We show that focusing on the <strong>top 20% of most likely opportunities lifts win rates from the 22.7% baseline to 51.7%</strong>; while focusing on the <strong>top 25% expected-value ranked opportunities captures 55.6% of total won revenue</strong>.</li>
<li>We recommend embedding scores in the CRM at opportunity creation, piloting via A/B test, and setting clear thresholds to operationalize prioritization in sales workflows.</li>
<li>We also simulate strategic levers under the static setup and find only modest upside, which reinforces that better process-history data is needed before using the models for bigger operating decisions.</li>
</ul>
</section>
<section id="agenda" class="slide level2 scrollable">
<h2>Agenda</h2>
<ol type="1">
<li>Business framing and process assumptions</li>
<li>EDA findings that matter for prioritization and forecasting</li>
<li>Modelling approach</li>
<li>Application scenarios</li>
<li>Conclusions and next steps</li>
</ol>
</section>
<section>
<section id="business-framing" class="title-slide slide level1 center" data-background-color="#0F172A">
<h1>Business framing</h1>

</section>
<section id="the-pipeline-is-non-linear-so-the-data-reflects-a-moving-sales-process" class="slide level2">
<h2>The pipeline is non-linear, so the data reflects a moving sales process</h2>
<div class="columns">
<div class="column" style="width:56%;">
<ul>
<li>The current sales process tracks auto-parts opportunities across both new leads and existing customers.</li>
<li>Opportunities transition between the stages Data entry → Identified / Qualifying → Qualified / Validating, and Validated / Gaining Agreement → Closed (Win/Loss).
<ul>
<li>Opportunities can move between stages in either direction, and they can also stall within a stage for extended periods.</li>
<li>Each opportunity ultimately resolves as either a win or a loss.</li>
<li>Sales teams maintain an estimated deal value, which is updated as the opportunity progresses.</li>
</ul></li>
</ul>
</div><div class="column" style="width:44%;">
<p><img data-src="assets/process.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="most-value-sits-in-a-small-share-of-opportunities-making-prioritization-an-important-growth-lever" class="slide level2">
<h2>Most value sits in a small share of opportunities making prioritization an important growth lever</h2>
<div class="columns">
<div class="column" style="width:56%;">
<h6 id="conversion-and-value-concentration-across-the-pipeline">Conversion and value concentration across the pipeline:</h6>
<p><img data-src="assets/eda_amount_win_rate.png" style="width:94.0%"></p>
</div><div class="column" style="width:44%;">
<ul>
<li>Low efficiency: only 22.7% conversion, indicating misallocated effort</li>
<li>Skewed deal mix: $94K avg vs $50K median → long tail of large deals</li>
<li>Value concentration: bigger deals win more → focus should shift</li>
<li>Clear opportunity: prioritize by win probability and deal size, ideally both</li>
<li>Implication: focus on the right deals, not more deals</li>
</ul>
</div></div>
</section>
<section id="we-focus-on-two-modelling-use-cases-prioritization-and-forecasting" class="slide level2">
<h2>We focus on two modelling use cases: prioritization and forecasting</h2>

<img data-src="assets/model_use_cases_overview.svg" style="width:100.0%" class="r-stretch"></section></section>
<section>
<section id="exploratory-data-analysis" class="title-slide slide level1 center" data-background-color="#0F172A">
<h1>Exploratory data analysis</h1>

</section>
<section id="the-data-is-sufficient-for-prioritization-and-directional-forecasting-despite-quality-issues" class="slide level2">
<h2>The data is sufficient for prioritization and directional forecasting, despite quality issues</h2>
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><strong>Scale</strong>: 78,025 sales opportunities and <strong>19 variables</strong> like:
<ul>
<li>at-start information: client size, opportunity type, product category, region, etc.</li>
<li>sales process details: elapsed time, stage changes, stage ratios, etc.</li>
<li>targets like amount and win/loss status.</li>
</ul></li>
<li>Validation removed duplicates and zero-amount opportunities prior to modelling; remaining data issues were intentionally retained.</li>
<li>For the modelling experiments shown here, the sample used <strong>75,819 eligible rows</strong> out of <strong>78,025 total rows</strong> with valid targets.</li>
</ul>
</div><div class="column" style="width:48%;">
<h6 id="row-counts-per-type-of-data-quality-issue">Row counts per type of data quality issue:</h6>
<p><img data-src="assets/annex_data_quality_issue_types.png" style="width:100.0%"></p>
</div></div>
<!-- - **What the data is good for**: ranking opportunities, understanding portfolio mix, and producing aggregate forecasts.
- **What it is not**: a full event history of every sales-stage movement.
- The dataset should therefore be read as a **current-state commercial view** of the pipeline. -->
</section>
<section id="tailor-commercial-treatment-by-client-size-scale-small-focus-high-value" class="slide level2">
<h2>Tailor commercial treatment by client size: scale small, focus high-value</h2>
<div class="columns">
<div class="column" style="width:58%;">
<h6 id="opportunity-counts-and-win-rates-by-client-size-segment">Opportunity counts and win rates by client-size segment:</h6>
<p><img data-src="assets/eda_client_segmentation.png" style="width:100.0%"></p>
</div><div class="column" style="width:42%;">
<ul>
<li>Most volume is ≤100K → scale this segment</li>
<li>Win rates are similar across sizes → use size for treatment, not targeting</li>
<li>Larger deals drive value → prioritize high-value accounts</li>
</ul>
</div></div>

<aside><div>
<p>Further causal work is needed to distinguish demand from historical sales focus.</p>
</div></aside></section>
<section id="treat-acquisition-and-expansion-as-distinct-growth-engines-each-with-its-own-playbook-and-resource-model." class="slide level2">
<h2>Treat acquisition and expansion as distinct growth engines, each with its own playbook and resource model.</h2>
<div class="columns">
<div class="column" style="width:42%;">
<ul>
<li><strong>(Re)Acquisition</strong> (no activity in 2 years): 69,208 opportunities, 17.3% win rate</li>
<li><strong>Engagement / upselling</strong>: 8,817 opportunities, 63.9% win rate</li>
<li>A practical first split: separates low-history acquisition from higher-propensity expansion.</li>
</ul>
</div><div class="column" style="width:58%;">
<h6 id="opportunity-counts-and-win-rates-by-funnel-stage">Opportunity counts and win rates by funnel stage:</h6>
<p><img data-src="assets/eda_two_phase_funnel.png" style="width:100.0%"></p>
</div></div>

<aside><div>
<p>Further causal work is needed to distinguish demand from historical sales focus.</p>
</div></aside></section>
<section id="performance-differences-are-driven-by-product-mix-not-geography" class="slide level2">
<h2>Performance differences are driven by product mix, not geography</h2>
<div class="columns">
<div class="column" style="width:70%;">
<h6 id="distribution-of-amount-and-win-rates-by-type-subtype-and-region">Distribution of amount and win rates by type, subtype, and region:</h6>
<p><img data-src="assets/eda_distribution_by_type_subtype_region.png" style="width:98.0%"></p>
</div><div class="column" style="font-size: 95%;">
<ul>
<li>Region is not a strong driver of conversion or deal size</li>
<li>Type and subtype drive meaningful variation in both outcomes</li>
<li>Prioritization should be product-driven, not geography-driven</li>
</ul>
</div></div>

<aside><div>
<p>Further causal work is needed to distinguish demand from historical sales focus.</p>
</div></aside></section>
<section id="the-strongest-predictors-of-win-and-amount-emerge-in-the-iv-analysis" class="slide level2">
<h2>The strongest predictors of win and amount emerge in the IV analysis</h2>
<div class="columns">
<div class="column" style="text-align:center;">
<p><img data-src="assets/eda_iv_classification.png" style="width:70.0%"></p>
</div><div class="column" style="text-align:center;">
<p><img data-src="assets/eda_iv_regression.png" style="width:70.0%"></p>
</div></div>
<ul>
<li>The left chart shows IVs against the <strong>win/loss target</strong>, while the right chart shows IVs against the <strong>amount target</strong>, using the full set of variables that enter the models.</li>
<li>Process-time variables and stage-ratio features remain among the strongest signals for classification, while the amount target includes product and client-size descriptors as strong predictors.</li>
</ul>

<aside><div>
<p>Further causal work is needed to distinguish demand from historical sales focus.</p>
</div></aside></section></section>
<section>
<section id="modelling" class="title-slide slide level1 center" data-background-color="#0F172A">
<h1>Modelling</h1>

</section>
<section id="we-prioritize-static-models-because-snapshot-timing-is-uncertain" class="slide level2">
<h2>We prioritize static models because snapshot timing is uncertain</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="static-pre-sales-process-model">Static / pre-sales process model</h3>
<ul>
<li>Used for <strong>early decisions</strong> at opportunity creation especially around prioritization and sizing.</li>
<li>Uses only <strong>at-creation variables</strong>: product / route / region / client-size / past-revenue descriptors.</li>
<li><strong>This is the setup used here.</strong> It is the safer operational choice when we cannot verify when the snapshot was taken.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="dynamic-during-sales-process-model">Dynamic / during sales process model</h3>
<ul>
<li>Used for <strong>ongoing re-prioritization and re-sizing</strong> during the process.</li>
<li>Uses the static variables <strong>plus process-state variables</strong>: elapsed time, stage changes, cumulative timing, and stage ratios.</li>
<li>It scores much better, but it is more exposed to timing leakage if the dataset snapshot is close to closure.</li>
<li>That version is kept in the <strong>annex as a reference benchmark</strong>.</li>
</ul>
</div></div>
<p><img data-src="assets/process22.png"></p>

<aside><div>
<p>Both approaches could use richer covariates, especially prior outcomes and process history per client.</p>
</div></aside></section>
<section id="model-performance-was-tested-on-a-realistic-held-out-sample" class="slide level2">
<h2>Model performance was tested on a realistic held-out sample</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><strong>Train / test split</strong>: <strong>70% / 30%</strong>
<ul>
<li>Train: 53,073 | Test: 22,746</li>
</ul></li>
<li>Stratified on win/loss and amount, keeping outcome balance and deal mix stable</li>
<li>5-fold CV on train, final evaluation on hold-out</li>
<li>Different preprocessing for X and y depending on model, same split for fair evaluation</li>
</ul>
</div><div class="column" style="width:46%;">
<h6 id="set-distribution-treemap">Set distribution treemap:</h6>
<p><img data-src="assets/model_split_treemap.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="static-prioritization-model-supports-earlier-safer-reallocation-of-sales-effort" class="slide level2">
<h2>Static prioritization model supports earlier, safer reallocation of sales effort</h2>
<div class="columns">
<div class="column" style="width:54%;">
<ul>
<li>Target: <strong>Opportunity Result</strong>.</li>
<li>Business use: <strong>early prioritization</strong> and ranking the pipeline by win propensity at opportunity creation.
<ul>
<li>Therefore we focused on ranking metrics such as ROC AUC and PR AUC.</li>
</ul></li>
<li>We used only <strong>at-creation variables</strong>, excluding process-timing fields and the amount target.</li>
<li>Selected final classifier: <strong>Calibrated Balanced Random Forest over the classic preprocessed feature set</strong> (<code>random_forest_classifier_balanced_calibrated</code>).</li>
<li>This model has <strong>moderate but usable</strong> performance for early triage (<strong>AUROC 73.6%, Accuracy 81.0% @ 54.5% threshold</strong>) versus the baselines (<strong>AUROC 50.0%, Accuracy 77.3%</strong> for the always-false classifier).</li>
</ul>
</div><div class="column" style="width:50%;">
<h6 id="classification-model-feature-importances">Classification model feature importances:</h6>
<p><img data-src="assets/classification_importance_static.png" style="width:100.0%"></p>
</div></div>

<aside><div>
<p>Selected calibrated balanced random forest for stronger probability quality under the safer static feature set.</p>
</div></aside></section>
<section id="static-prioritization-model-supports-earlier-safer-reallocation-of-sales-effort-cont.-with-performance-metrics" class="slide level2">
<h2>Static prioritization model supports earlier, safer reallocation of sales effort (cont., with performance metrics)</h2>
<div class="columns">
<div class="column" style="width:57%;">
<div style="font-size: 70%;">
<p>The following table shows the selected model’s performance on both CV and held-out test, compared to random and simple baselines:</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Split</th>
<th style="text-align: right;">ROC AUC</th>
<th style="text-align: right;">PR AUC</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Selected</td>
<td>CV</td>
<td style="text-align: right;">74.0%</td>
<td style="text-align: right;">52.6%</td>
<td style="text-align: right;">80.9%</td>
<td style="text-align: right;">73.4%</td>
<td style="text-align: right;">25.0%</td>
<td style="text-align: right;">37.3%</td>
</tr>
<tr class="even">
<td>Selected</td>
<td>Held-out test</td>
<td style="text-align: right;">73.6%</td>
<td style="text-align: right;">52.8%</td>
<td style="text-align: right;">81.0%</td>
<td style="text-align: right;">73.5%</td>
<td style="text-align: right;">25.3%</td>
<td style="text-align: right;">37.6%</td>
</tr>
<tr class="odd">
<td>Random baseline</td>
<td>Held-out test</td>
<td style="text-align: right;">50.5%</td>
<td style="text-align: right;">22.9%</td>
<td style="text-align: right;">65.1%</td>
<td style="text-align: right;">23.5%</td>
<td style="text-align: right;">23.6%</td>
<td style="text-align: right;">23.5%</td>
</tr>
<tr class="even">
<td>Always false baseline</td>
<td>Held-out test</td>
<td style="text-align: right;">50.0%</td>
<td style="text-align: right;">22.7%</td>
<td style="text-align: right;">77.3%</td>
<td style="text-align: right;">0.0%</td>
<td style="text-align: right;">0.0%</td>
<td style="text-align: right;">0.0%</td>
</tr>
<tr class="odd">
<td>Always true baseline</td>
<td>Held-out test</td>
<td style="text-align: right;">50.0%</td>
<td style="text-align: right;">22.7%</td>
<td style="text-align: right;">22.7%</td>
<td style="text-align: right;">22.7%</td>
<td style="text-align: right;">100.0%</td>
<td style="text-align: right;">37.0%</td>
</tr>
</tbody>
</table>
<p><br></p>
<div style="font-size: 80%;">
<p>Conclusions:</p>
<ul>
<li>The model has enough ranking signal (<strong>AUROC 73.6% on hold-out</strong>) to support early screening, and it uses a more precision-oriented operating threshold because the business action is to focus scarce sales effort.</li>
</ul>
</div>
</div>
</div><div class="column" style="width:43%;">
<p><img data-src="assets/classification_roc_static.png" style="width:100.0%"></p>
</div></div>

<aside><div>
<p>Selected threshold is <strong>54.5%</strong> on training OOF predictions, chosen to maximize precision subject to at least <strong>25% recall</strong>; the old dynamic calibration and hold-out diagnostics are kept in the annex for reference.</p>
</div></aside></section>
<section id="use-the-amount-model-for-per-opportunity-sizing-and-ranking-not-deal-level-precision" class="slide level2">
<h2>Use the amount model for per-opportunity sizing and ranking, not deal-level precision</h2>
<div class="columns">
<div class="column" style="width:54%;">
<ul>
<li>Target: <strong>Opportunity Amount USD</strong>.</li>
<li>Business use: <strong>sizing and directional forecasting</strong>.
<ul>
<li>Therefore we focused on error metrics such as MAE and especially MAPE since it is scale-invariant and better captures the relative error across the wide deal-size distribution.</li>
</ul></li>
<li>We used only <strong>at-creation variables</strong>, excluding process-timing fields and the win/loss target.</li>
<li>Selected final regression model: <strong>Yeo-Johnson transformed XGBoost regressor</strong> (<code>xgboost_yeojohnson</code>), selected by lowest CV Median APE.</li>
<li>The model beats simple baselines on MAE and Median APE, <strong>but with R² ≈ 0.04, MAE ≈ 66.7k USD, and Median APE ≈ 63%</strong>, deal-level precision remains weak, so the best use case is directional sizing and ranking rather than exact deal-level forecasts.</li>
</ul>
</div><div class="column" style="width:46%;">
<h6 id="amount-model-feature-importances">Amount model feature importances:</h6>
<p><img data-src="assets/regression_importance_static.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="use-the-amount-model-for-per-opportunity-sizing-and-ranking-not-deal-level-precision-cont.-with-performance-metrics" class="slide level2">
<h2>Use the amount model for per-opportunity sizing and ranking, not deal-level precision (cont., with performance metrics)</h2>
<div class="columns">
<div class="column" style="width:54%;">
<div style="font-size: 80%;">
<p>The following table shows the selected model’s performance on both CV and held-out test:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Split</th>
<th style="text-align: right;">R²</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">Median APE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Selected</td>
<td style="text-align: right;">CV</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">66.7k USD</td>
<td style="text-align: right;">63.1%</td>
</tr>
<tr class="even">
<td>Selected</td>
<td style="text-align: right;">Held-out test</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">66.7k USD</td>
<td style="text-align: right;">63.0%</td>
</tr>
<tr class="odd">
<td>Mean baseline</td>
<td style="text-align: right;">Held-out test</td>
<td style="text-align: right;">-0.000</td>
<td style="text-align: right;">84.9k USD</td>
<td style="text-align: right;">88.3%</td>
</tr>
<tr class="even">
<td>Median baseline</td>
<td style="text-align: right;">Held-out test</td>
<td style="text-align: right;">-0.108</td>
<td style="text-align: right;">74.9k USD</td>
<td style="text-align: right;">75.0%</td>
</tr>
<tr class="odd">
<td>Random baseline</td>
<td style="text-align: right;">Held-out test</td>
<td style="text-align: right;">-0.972</td>
<td style="text-align: right;">113.4k USD</td>
<td style="text-align: right;">90.1%</td>
</tr>
</tbody>
</table>
<p><br></p>
<h6 id="conclusions">Conclusions:</h6>
<ul>
<li>Model is more useful for relative sizing and ranking than for exact portfolio totals, which remains the tradeoff from selecting by Median APE.
<ul>
<li>Aggregate actual amount: <strong>2.138B USD</strong> on the held-out test set.</li>
<li>Aggregate predicted amount: <strong>1.279B USD</strong> on the held-out test set.</li>
<li>Mean absolute error per opportunity: <strong>66.7k USD</strong>.</li>
</ul></li>
</ul>
</div>
</div><div class="column" style="width:46%;">
<h6 id="forecast-vs-actual-scatter-plot">Forecast vs actual scatter plot:</h6>
<p><img data-src="assets/sim_forecasting_static.png" style="width:100.0%"></p>
</div></div>

<aside><div>
<p>The annex keeps the old dynamic validation artifacts for comparison; the main takeaway here is that the static amount model is still directional, not precise.</p>
</div></aside></section></section>
<section>
<section id="application-scenarios" class="title-slide slide level1 center" data-background-color="#1E293B">
<h1>Application scenarios</h1>

</section>
<section id="more-than-doubling-conversion-is-achievable-by-focusing-on-the-top-20-of-opportunities-without-increasing-pipeline-size" class="slide level2">
<h2>More than doubling conversion is achievable by focusing on the top 20% of opportunities, without increasing pipeline size</h2>
<div class="columns">
<div class="column" style="width:44%;">
<ul>
<li>Sales effort is currently spread across low-probability deals → concentrating on the top-scored opportunities can raise conversion efficiency.
<ul>
<li><strong>Top 20%</strong> of opportunities: <strong>51.7%</strong> conversion vs <strong>22.7%</strong> baseline (<strong>2.27× lift</strong>).</li>
</ul></li>
</ul>

</div><div class="column" style="width:56%;">
<p><img data-src="assets/sim_prioritization_static.png" style="width:100.0%"></p>
</div></div>
<aside><div>
<p>This simulation is based on held-out test-set predictions.</p>
</div></aside></section>
<section id="concentration-38-value-capture-at-top-10-still-makes-expected-value-prioritization-useful" class="slide level2">
<h2>Concentration (~38% value capture at top 10%) still makes expected-value prioritization useful</h2>
<div class="columns">
<div class="column" style="width:56%;">
<p><img data-src="assets/sim_expected_value_threshold_static.png" style="width:80.0%"></p>
</div><div class="column" style="width:44%;">
<ul>
<li>Rank the pipeline using expected value (E[Amount] × P(Win)), not just propensity especially under limited sales capacity.
<ul>
<li>At top 10%, expected-value ranking captures <strong>37.9%</strong> of won revenue vs <strong>31.4%</strong> with propensity-only.</li>
<li>By top 25%, expected-value ranking captures <strong>56.0%</strong> of won revenue, after which the curve starts to flatten.</li>
</ul></li>
</ul>
</div></div>

<aside><div>
<p>Based on held-out test-set predictions; assumes opportunity amount reflects final deal value, which may not hold.</p>
</div></aside></section>
<section id="combining-model-outputs-creates-actionable-commercial-segments" class="slide level2">
<h2>Combining model outputs creates actionable commercial segments</h2>
<div class="columns">
<div class="column" style="width:62%;">
<p><img data-src="assets/annex_ev_probability_quadrants_static.png" style="width:100.0%"></p>
</div><div class="column" style="width:38%;">
<ul>
<li>Simple split, still useful: Combining expected value and win probability separates opportunities into workable commercial tiers even with the weaker static model.</li>
<li>Clear but more modest performance differences: each segment still shows different conversion rates and revenue contribution.</li>
<li>Direct CRM translation: Segments map to actions like intervene, focus, accelerate, or deprioritize.</li>
<li>Operational, not theoretical: This provides a practical decision layer for sales, not just model output.</li>
</ul>
</div></div>

<aside><div>
<p>Based on held-out test-set predictions; assumes opportunity amount reflects final deal value, which may not hold.</p>
</div></aside></section>
<section id="model-outputs-should-be-automatically-embedded-in-the-crm" class="slide level2">
<h2>Model outputs should be automatically embedded in the CRM</h2>

<img data-src="assets/crm_embedding_quadrants.svg" style="width:100.0%" class="r-stretch"></section>
<section id="model-outputs-can-inform-broader-commercial-strategy" class="slide level2">
<h2>Model outputs can inform broader commercial strategy</h2>
<div class="columns">
<div class="column" style="width:58%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/strategic_lever_focus_summary_static.png" class="quarto-figure quarto-figure-center" style="width:50.0%"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/strategic_lever_salesforce_summary_static.png" class="quarto-figure quarto-figure-center" style="width:50.0%"></p>
</figure>
</div>
</div><div class="column" style="width:42%;">
<ul>
<li><strong>Lever 1, Focus the team:</strong> Under the static ranking with a stronger focus-gain assumption (<strong>λ_max = 2.0×</strong>), the upside becomes more visible. Best simulated point is <strong>top ~56%</strong> of the ranked pipeline, reaching <strong>$436M</strong> in revenue, or about <strong>+$51M vs.&nbsp;baseline</strong>.</li>
<li><strong>Lever 2, Optimize salesforce size:</strong> With a richer contribution formula and a more realistic comp structure, the headcount signal is still modest but more realistic. Best simulated point is <strong>221 reps</strong>, retaining <strong>99.7%</strong> of revenue and improving contribution margin by <strong>~+$1.2M</strong> vs.&nbsp;baseline.
<ul>
<li>Another option is segmenting the salesforce, with a specialized team focused on high-value opportunities/accounts and another team managing the rest.</li>
</ul></li>
</ul>
</div></div>

<aside><div>
<p>Held-out predictions; Lever 1 uses a decaying focus gain (<strong>2.0×→1.0×</strong>), while Lever 2 uses a practical contribution formula with base+overhead rep cost, commission, acquisition, and serving costs.</p>
</div></aside></section>
<section id="these-simulations-show-business-potential-not-final-operating-estimates" class="slide level2">
<h2>These simulations show business potential, not final operating estimates</h2>
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><strong>Simulations are based on held-out observational predictions</strong>, so they are weaker than an actual backtest and/or experiment and they cannot capture the full causal impact of acting on model outputs.</li>
<li><strong>Potentially relevant covariates are missing</strong>: the dataset lacks important drivers such as richer account history, rep behavior, pricing context, and external market conditions.</li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li><strong>Dynamic results are kept in the annex as a benchmark</strong>, because they are much stronger example of how the models could perform under ideal conditions, but also more exposed to timing leakage if the snapshot was taken late in the sales process.</li>
<li><strong>Missing business context</strong>: key factors such as sales capacity, cost structure, pricing, and CRM integration were not incorporated or validated with business stakeholders, limiting real-world applicability.</li>
</ul>
</div></div>
</section></section>
<section>
<section id="conclusions-1" class="title-slide slide level1 center" data-background-color="#0F172A">
<h1>Conclusions</h1>

</section>
<section id="key-takeaways-for-commercial-decision-making" class="slide level2">
<h2>Key takeaways for commercial decision-making</h2>
<ul>
<li>Prioritization is the highest-impact, low-effort lever</li>
<li>Win/loss model (moderate scoring performance, AUROC 73.6%) still improves focus early in the process
<ul>
<li>Top 20% opportunities go from <strong>~22.7% win rate (baseline) to ~51.7%</strong></li>
</ul></li>
<li>Use the amount model directionally, not for forecasting
<ul>
<li>63.0% MdAPE per deal and ~40% under-forecast at portfolio level</li>
</ul></li>
<li>Expected value is the strongest prioritization approach
<ul>
<li>Outperforms individual models for value capture</li>
</ul></li>
<li>Revenues are still concentrated <strong>(~38% top 10% opp., ~56% top 25% opp.)</strong> and should be prioritized accordingly</li>
<li>Implications for commercial strategy:
<ul>
<li>Focus efforts on the best opportunities first</li>
<li>Treat bigger strategic levers cautiously until richer process-history data is available</li>
</ul></li>
<li>Recommendations for implementing model-driven sales:
<ul>
<li>Always embed through CRM.</li>
<li>[1] Pilot static prioritization first, then [2] add the amount model for sizing and ranking and finally, [3] combine into expected-value prioritization to guide focus and resource allocation.</li>
<li><strong>(Optional but recommended)</strong> Keep an experimental mindset and run A/B tests continuously to validate the impact of acting on model outputs, and also to collect contrafactual data to improve the models over time.</li>
</ul></li>
</ul>
</section>
<section id="next-steps-how-to-operationalize-model-driven-sales" class="slide level2">
<h2>Next steps: how to operationalize model-driven sales</h2>

<img data-src="assets/next_steps_operationalize_timeline.svg" style="width:100.0%" class="r-stretch"></section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#0F172A">
<h1>Thank you</h1>
<p>Questions, comments, and feedback are welcome!</p>
</section>

<section>
<section id="annex" class="title-slide slide level1 center" data-background-color="#0F172A">
<h1>Annex</h1>

</section>
<section id="annex-static-classification-cv-leaderboard" class="slide level2">
<h2>Annex: static classification CV leaderboard</h2>
<div style="font-size: 80%;">
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">ROC AUC</th>
<th style="text-align: right;">PR AUC</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>random_forest_classifier_balanced_calibrated</td>
<td style="text-align: right;"><strong>74.0% ± 0.6%</strong></td>
<td style="text-align: right;"><strong>52.6% ± 1.3%</strong></td>
<td style="text-align: right;"><strong>81.0% ± 0.4%</strong></td>
<td style="text-align: right;">70.5% ± 1.8%</td>
<td style="text-align: right;">28.0% ± 1.1%</td>
<td style="text-align: right;">40.1% ± 1.4%</td>
</tr>
<tr class="even">
<td>random_forest_classifier</td>
<td style="text-align: right;">73.9% ± 0.7%</td>
<td style="text-align: right;">52.5% ± 1.3%</td>
<td style="text-align: right;">72.1% ± 0.4%</td>
<td style="text-align: right;">41.9% ± 0.8%</td>
<td style="text-align: right;"><strong>58.7% ± 1.3%</strong></td>
<td style="text-align: right;"><strong>48.8% ± 0.9%</strong></td>
</tr>
<tr class="odd">
<td>random_forest_classifier_balanced</td>
<td style="text-align: right;">73.9% ± 0.7%</td>
<td style="text-align: right;">52.5% ± 1.3%</td>
<td style="text-align: right;">72.1% ± 0.4%</td>
<td style="text-align: right;">41.9% ± 0.8%</td>
<td style="text-align: right;"><strong>58.7% ± 1.3%</strong></td>
<td style="text-align: right;"><strong>48.8% ± 0.9%</strong></td>
</tr>
<tr class="even">
<td>xgboost</td>
<td style="text-align: right;">73.5% ± 0.6%</td>
<td style="text-align: right;">51.8% ± 1.5%</td>
<td style="text-align: right;">80.8% ± 0.5%</td>
<td style="text-align: right;"><strong>71.5% ± 1.4%</strong></td>
<td style="text-align: right;">26.4% ± 2.3%</td>
<td style="text-align: right;">38.8% ± 2.6%</td>
</tr>
<tr class="odd">
<td>xgboost_balanced</td>
<td style="text-align: right;">73.3% ± 0.8%</td>
<td style="text-align: right;">51.7% ± 1.5%</td>
<td style="text-align: right;">71.2% ± 0.7%</td>
<td style="text-align: right;">40.3% ± 0.8%</td>
<td style="text-align: right;">58.2% ± 1.6%</td>
<td style="text-align: right;">47.6% ± 0.5%</td>
</tr>
<tr class="even">
<td>logit_elasticnet_robust_scaler_balanced</td>
<td style="text-align: right;">72.5% ± 0.5%</td>
<td style="text-align: right;">50.9% ± 1.2%</td>
<td style="text-align: right;">71.1% ± 0.7%</td>
<td style="text-align: right;">40.4% ± 0.6%</td>
<td style="text-align: right;">56.7% ± 2.4%</td>
<td style="text-align: right;">47.1% ± 0.8%</td>
</tr>
<tr class="odd">
<td>logit_elasticnet_robust_scaler</td>
<td style="text-align: right;">72.4% ± 0.5%</td>
<td style="text-align: right;">50.9% ± 1.2%</td>
<td style="text-align: right;">80.9% ± 0.4%</td>
<td style="text-align: right;">70.9% ± 1.6%</td>
<td style="text-align: right;">26.7% ± 1.7%</td>
<td style="text-align: right;">38.8% ± 2.0%</td>
</tr>
<tr class="even">
<td>classic_logit_robust_scaler</td>
<td style="text-align: right;">72.4% ± 0.5%</td>
<td style="text-align: right;">50.9% ± 1.2%</td>
<td style="text-align: right;">80.9% ± 0.4%</td>
<td style="text-align: right;">70.9% ± 1.6%</td>
<td style="text-align: right;">26.8% ± 1.6%</td>
<td style="text-align: right;">38.8% ± 1.9%</td>
</tr>
<tr class="odd">
<td>logit_elasticnet_binned_ohe_balanced</td>
<td style="text-align: right;">72.4% ± 0.5%</td>
<td style="text-align: right;">50.1% ± 0.9%</td>
<td style="text-align: right;">70.5% ± 0.6%</td>
<td style="text-align: right;">39.7% ± 0.5%</td>
<td style="text-align: right;">57.3% ± 2.4%</td>
<td style="text-align: right;">46.9% ± 0.7%</td>
</tr>
<tr class="even">
<td>logit_binned_ohe_balanced</td>
<td style="text-align: right;">72.4% ± 0.5%</td>
<td style="text-align: right;">50.1% ± 0.9%</td>
<td style="text-align: right;">70.5% ± 0.6%</td>
<td style="text-align: right;">39.7% ± 0.5%</td>
<td style="text-align: right;">57.4% ± 2.4%</td>
<td style="text-align: right;">46.9% ± 0.7%</td>
</tr>
<tr class="odd">
<td>logit_binned_ohe_balanced_calibrated</td>
<td style="text-align: right;">72.4% ± 0.5%</td>
<td style="text-align: right;">50.1% ± 0.9%</td>
<td style="text-align: right;">80.6% ± 0.3%</td>
<td style="text-align: right;">68.2% ± 2.5%</td>
<td style="text-align: right;">27.5% ± 3.1%</td>
<td style="text-align: right;">39.0% ± 2.9%</td>
</tr>
<tr class="even">
<td>logit_elasticnet_binned_ohe</td>
<td style="text-align: right;">72.3% ± 0.4%</td>
<td style="text-align: right;">50.1% ± 0.9%</td>
<td style="text-align: right;">80.6% ± 0.4%</td>
<td style="text-align: right;">68.3% ± 2.5%</td>
<td style="text-align: right;">27.8% ± 3.3%</td>
<td style="text-align: right;">39.4% ± 3.1%</td>
</tr>
<tr class="odd">
<td>logit_binned_ohe</td>
<td style="text-align: right;">72.3% ± 0.4%</td>
<td style="text-align: right;">50.1% ± 0.9%</td>
<td style="text-align: right;">80.6% ± 0.4%</td>
<td style="text-align: right;">68.2% ± 2.4%</td>
<td style="text-align: right;">27.8% ± 3.2%</td>
<td style="text-align: right;">39.4% ± 3.1%</td>
</tr>
<tr class="even">
<td>logit_elastic_binned_woe_balanced</td>
<td style="text-align: right;">71.2% ± 0.5%</td>
<td style="text-align: right;">49.7% ± 0.8%</td>
<td style="text-align: right;">69.5% ± 0.8%</td>
<td style="text-align: right;">38.4% ± 0.6%</td>
<td style="text-align: right;">56.7% ± 2.2%</td>
<td style="text-align: right;">45.8% ± 0.3%</td>
</tr>
<tr class="odd">
<td>logit_elastic_binned_woe</td>
<td style="text-align: right;">71.2% ± 0.5%</td>
<td style="text-align: right;">49.7% ± 0.8%</td>
<td style="text-align: right;">80.7% ± 0.4%</td>
<td style="text-align: right;">68.3% ± 3.2%</td>
<td style="text-align: right;">28.2% ± 4.3%</td>
<td style="text-align: right;">39.7% ± 4.0%</td>
</tr>
<tr class="even">
<td>logit_binned_woe</td>
<td style="text-align: right;">71.2% ± 0.5%</td>
<td style="text-align: right;">49.7% ± 0.8%</td>
<td style="text-align: right;">80.6% ± 0.3%</td>
<td style="text-align: right;">68.3% ± 3.2%</td>
<td style="text-align: right;">28.2% ± 4.3%</td>
<td style="text-align: right;">39.7% ± 4.0%</td>
</tr>
<tr class="odd">
<td>random_classifier</td>
<td style="text-align: right;">50.2% ± 0.2%</td>
<td style="text-align: right;">22.8% ± 0.1%</td>
<td style="text-align: right;">65.4% ± 0.1%</td>
<td style="text-align: right;">23.0% ± 0.3%</td>
<td style="text-align: right;">22.4% ± 0.3%</td>
<td style="text-align: right;">22.7% ± 0.3%</td>
</tr>
<tr class="even">
<td>always_true_classifier</td>
<td style="text-align: right;">50.0% ± 0.0%</td>
<td style="text-align: right;">22.7% ± 0.0%</td>
<td style="text-align: right;">22.7% ± 0.0%</td>
<td style="text-align: right;">22.7% ± 0.0%</td>
<td style="text-align: right;">100.0% ± 0.0%</td>
<td style="text-align: right;">37.0% ± 0.0%</td>
</tr>
</tbody>
</table>
<p>Selected model in the current main deck: <strong>random_forest_classifier_balanced_calibrated</strong>.</p>
</div>
</section>
<section id="annex-static-regression-cv-leaderboard" class="slide level2">
<h2>Annex: static regression CV leaderboard</h2>
<div style="font-size: 80%;">
<table class="caption-top">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">R²</th>
<th style="text-align: right;">MAE (USD)</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">Median APE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>xgboost_yeojohnson</td>
<td style="text-align: right;">0.041 ± 0.009</td>
<td style="text-align: right;">66.7k ± 1.5k</td>
<td style="text-align: right;">158.4% ± 22.3%</td>
<td style="text-align: right;">63.1%</td>
</tr>
<tr class="even">
<td>xgboost_boxcox</td>
<td style="text-align: right;">0.041 ± 0.009</td>
<td style="text-align: right;">66.7k ± 1.5k</td>
<td style="text-align: right;">158.7% ± 23.9%</td>
<td style="text-align: right;">63.1%</td>
</tr>
<tr class="odd">
<td>xgboost_log1p</td>
<td style="text-align: right;">-0.007 ± 0.009</td>
<td style="text-align: right;">67.6k ± 1.6k</td>
<td style="text-align: right;">126.4% ± 19.5%</td>
<td style="text-align: right;">63.5%</td>
</tr>
<tr class="even">
<td>classic_linear_boxcox_robust_scaler</td>
<td style="text-align: right;">0.031 ± 0.009</td>
<td style="text-align: right;">67.4k ± 1.5k</td>
<td style="text-align: right;">173.5% ± 28.9%</td>
<td style="text-align: right;">63.8%</td>
</tr>
<tr class="odd">
<td>classic_linear_yeojohnson_robust_scaler</td>
<td style="text-align: right;">0.031 ± 0.009</td>
<td style="text-align: right;">67.4k ± 1.5k</td>
<td style="text-align: right;">173.4% ± 28.9%</td>
<td style="text-align: right;">63.8%</td>
</tr>
<tr class="even">
<td>linear_power_scaler_binned_ohe</td>
<td style="text-align: right;">0.029 ± 0.009</td>
<td style="text-align: right;">67.5k ± 1.5k</td>
<td style="text-align: right;">176.8% ± 30.4%</td>
<td style="text-align: right;">63.9%</td>
</tr>
<tr class="odd">
<td>classic_linear_log1p_robust_scaler</td>
<td style="text-align: right;">-0.017 ± 0.008</td>
<td style="text-align: right;">68.3k ± 1.6k</td>
<td style="text-align: right;">144.6% ± 24.8%</td>
<td style="text-align: right;">64.4%</td>
</tr>
<tr class="even">
<td>median_regressor</td>
<td style="text-align: right;">-0.108 ± 0.002</td>
<td style="text-align: right;">75.0k ± 1.5k</td>
<td style="text-align: right;">124.7% ± 28.4%</td>
<td style="text-align: right;">74.6%</td>
</tr>
<tr class="odd">
<td>random_forest_regressor</td>
<td style="text-align: right;">0.124 ± 0.009</td>
<td style="text-align: right;">74.2k ± 1.1k</td>
<td style="text-align: right;">283.4% ± 44.4%</td>
<td style="text-align: right;">77.5%</td>
</tr>
<tr class="even">
<td>xgboost</td>
<td style="text-align: right;">0.136 ± 0.008</td>
<td style="text-align: right;">73.8k ± 1.0k</td>
<td style="text-align: right;">289.3% ± 46.0%</td>
<td style="text-align: right;">78.6%</td>
</tr>
<tr class="odd">
<td>linear_binned_ohe</td>
<td style="text-align: right;">0.127 ± 0.008</td>
<td style="text-align: right;">74.7k ± 1.0k</td>
<td style="text-align: right;">298.7% ± 52.5%</td>
<td style="text-align: right;">78.6%</td>
</tr>
<tr class="even">
<td>classic_linear_robust_scaler</td>
<td style="text-align: right;">0.128 ± 0.007</td>
<td style="text-align: right;">74.7k ± 1.1k</td>
<td style="text-align: right;">295.1% ± 50.2%</td>
<td style="text-align: right;">78.7%</td>
</tr>
<tr class="odd">
<td>linear_binned_woe_robust_scaler</td>
<td style="text-align: right;">0.124 ± 0.008</td>
<td style="text-align: right;">74.8k ± 1.1k</td>
<td style="text-align: right;">298.7% ± 56.6%</td>
<td style="text-align: right;">79.1%</td>
</tr>
<tr class="even">
<td>elastic_binned_woe</td>
<td style="text-align: right;">0.124 ± 0.008</td>
<td style="text-align: right;">74.8k ± 1.1k</td>
<td style="text-align: right;">298.7% ± 56.6%</td>
<td style="text-align: right;">79.1%</td>
</tr>
<tr class="odd">
<td>mean_regressor</td>
<td style="text-align: right;">-0.000 ± 0.000</td>
<td style="text-align: right;">84.9k ± 1.3k</td>
<td style="text-align: right;">235.0% ± 53.9%</td>
<td style="text-align: right;">88.3%</td>
</tr>
<tr class="even">
<td>random_regressor</td>
<td style="text-align: right;">-1.053 ± 0.057</td>
<td style="text-align: right;">115.0k ± 2.1k</td>
<td style="text-align: right;">164.1% ± 65.3%</td>
<td style="text-align: right;">90.4%</td>
</tr>
<tr class="odd">
<td>xgboost_pseudohubererror</td>
<td style="text-align: right;">-0.473 ± 0.011</td>
<td style="text-align: right;">92.3k ± 2.0k</td>
<td style="text-align: right;">5.3% ± 1.2%</td>
<td style="text-align: right;">96.1%</td>
</tr>
<tr class="even">
<td>elasticnet_robust_scaler</td>
<td style="text-align: right;">0.058 ± 0.003</td>
<td style="text-align: right;">80.2k ± 1.2k</td>
<td style="text-align: right;">260.0% ± 54.5%</td>
<td style="text-align: right;">99.0%</td>
</tr>
</tbody>
</table>
<p>Selected model in the current main deck: <strong>xgboost_yeojohnson</strong> by CV Median APE.</p>
</div>
</section>
<section id="annex-static-hold-out-calibration-of-the-selected-classifier" class="slide level2">
<h2>Annex: static hold-out calibration of the selected classifier</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><img data-src="assets/annex_calibration_comparison_static.png" style="width:100.0%"></p>
</div><div class="column" style="width:42%;">
<ul>
<li>This chart shows the <strong>selected static classifier itself</strong> on the held-out set: <code>random_forest_classifier_balanced_calibrated</code>.</li>
<li>It compares the model’s mean predicted win probability to the observed win rate across quantile bins.</li>
<li>The closer the curve sits to the 45-degree reference, the more usable the probabilities are for thresholding and expected-value calculations.</li>
</ul>
</div></div>
</section>
<section id="annex-static-hold-out-classification-report-at-the-selected-models-optimal-threshold" class="slide level2">
<h2>Annex: static hold-out classification report at the selected model’s optimal threshold</h2>
<div class="smallest">
<p>Threshold chosen on <strong>training out-of-fold predictions</strong> to maximize <strong>precision subject to recall ≥ 25%</strong> for the selected model: <strong>54.5%</strong> predicted win probability.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Threshold</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Selected @ optimal threshold</td>
<td style="text-align: right;">54.5%</td>
<td style="text-align: right;">81.0%</td>
<td style="text-align: right;">73.5%</td>
<td style="text-align: right;">25.3%</td>
<td style="text-align: right;">37.6%</td>
</tr>
<tr class="even">
<td>Random classifier</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">65.1%</td>
<td style="text-align: right;">23.5%</td>
<td style="text-align: right;">23.6%</td>
<td style="text-align: right;">23.5%</td>
</tr>
<tr class="odd">
<td>Always false</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">77.3%</td>
<td style="text-align: right;">0.0%</td>
<td style="text-align: right;">0.0%</td>
<td style="text-align: right;">0.0%</td>
</tr>
<tr class="even">
<td>Always true</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">22.7%</td>
<td style="text-align: right;">22.7%</td>
<td style="text-align: right;">100.0%</td>
<td style="text-align: right;">37.0%</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">TN</th>
<th style="text-align: right;">FP</th>
<th style="text-align: right;">FN</th>
<th style="text-align: right;">TP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Selected @ optimal threshold</td>
<td style="text-align: right;">17,104</td>
<td style="text-align: right;">472</td>
<td style="text-align: right;">3,860</td>
<td style="text-align: right;">1,310</td>
</tr>
<tr class="even">
<td>Random classifier</td>
<td style="text-align: right;">13,597</td>
<td style="text-align: right;">3,979</td>
<td style="text-align: right;">3,951</td>
<td style="text-align: right;">1,219</td>
</tr>
<tr class="odd">
<td>Always false</td>
<td style="text-align: right;">17,576</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5,170</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>Always true</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">17,576</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5,170</td>
</tr>
</tbody>
</table>
<p>Diagnostic note: the threshold is selected on train-side OOF predictions, then evaluated once on the untouched hold-out set shown here.</p>
</div>
</section>
<section id="annex-static-regression-error-by-amount-bin-on-the-hold-out-set" class="slide level2">
<h2>Annex: static regression error by amount bin on the hold-out set</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><img data-src="assets/annex_regression_error_bins_static.png" style="width:100.0%"></p>
</div><div class="column" style="width:42%;">
<ul>
<li>The comparison shows where model error changes most across deal-size bands, instead of averaging everything into one MAE figure.</li>
<li>Under the static setup, the transformed XGBoost variants still lead the relative-error ranking, with <strong>XGBoost Yeo-Johnson</strong> narrowly selected overall.</li>
<li>The main gain still comes from controlling typical proportional error, while the largest opportunities continue to create a gap between deal-level accuracy and total-portfolio forecasting.</li>
</ul>
</div></div>
</section>
<section id="annex-static-held-out-forecast-bias-of-the-selected-amount-model" class="slide level2">
<h2>Annex: static held-out forecast bias of the selected amount model</h2>
<div class="columns">
<div class="column" style="width:56%;">
<p><img data-src="assets/annex_forecast_bias_static.png" style="width:100.0%"></p>
</div><div class="column" style="width:44%;">
<ul>
<li>The selected static amount model under-forecasts the held-out portfolio: <strong>$1.28B predicted</strong> vs <strong>$2.14B actual</strong>.</li>
<li>That is a gap of about <strong>$859M</strong>, or roughly <strong>40% below</strong> the realized total on the test set.</li>
<li>This is why the main deck uses the amount model for <strong>directional sizing and ranking</strong>, not as a committed aggregate forecast without an explicit bias-correction layer.</li>
<li>The same hold-out evaluation still supports the model for per-opportunity ordering because <strong>MAE ≈ $66.7K</strong> and <strong>Median APE ≈ 63%</strong> are judged at deal level, not portfolio-total calibration.</li>
</ul>
</div></div>
</section>
<section id="annex-data-quality-issue-profile-from-the-validation-notebook" class="slide level2">
<h2>Annex: data-quality issue profile from the validation notebook</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="assets/number_of_problems.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="assets/annex_data_quality_issue_types.png" style="width:100.0%"></p>
</div></div>
<ul>
<li>Source of truth: <code>notebooks/1_data_validation_and_cleaning/01_basic_validation.ipynb</code>, which builds <code>problem_tags</code>, <code>problem_count</code>, and the row-level validation flags before exporting <code>cleaned_data.parquet</code>.</li>
<li>The row-count distribution shows that most records have <strong>0–1 detected issues</strong>, while the issue-type breakdown shows that the main burden comes from <strong>stage-ratio inconsistencies</strong>, <strong>amount weirdness</strong>, and <strong>only-identified-stage</strong> records.</li>
<li>This supports the data-prep choice used throughout the deck: remove clearly unusable rows (duplicates, invalid targets) but retain many imperfect rows with explicit flags because the modeling task is ranking and prioritization, not accounting-grade reconciliation.</li>
</ul>
</section>
<section id="annex-numeric-variable-correlation-heatmap" class="slide level2">
<h2>Annex: numeric variable correlation heatmap</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="assets/annex_numeric_correlation_heatmap.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<ul>
<li>Most numeric relationships are weak, suggesting limited linear redundancy across variables.</li>
<li>Process-duration variables are highly correlated (e.g.&nbsp;identified→closing vs identified→qualified), so they likely capture overlapping timing effects.</li>
<li>Stage-ratio variables show expected inverse relationships, reflecting how progress through the funnel mechanically shifts the composition of stage shares.</li>
</ul>
</div></div>
</section>
<section id="annex-strategic-lever-1-focus-the-same-team-on-fewer-better-ranked-deals" class="slide level2">
<h2>Annex: strategic lever 1 — focus the same team on fewer, better-ranked deals</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><img data-src="assets/sim_focus_gain_main_static.png" style="width:88.0%"></p>
</div><div class="column" style="width:45%;">
<ul>
<li>Same salesforce, fewer deals — dropped opportunities go unworked.</li>
<li>Focus gain grows as the slice shrinks (λ_max = 2.0× at top slice → 1.0× at full pipeline).</li>
<li>Break-even at <strong>top ~28%</strong>; optimal at <strong>top ~56%</strong> → <strong>$436M</strong> (+$51M vs.&nbsp;baseline).</li>
</ul>
</div></div>

<aside><div>
<p>Focus-gain λ_max is a scenario assumption, not an empirically estimated causal effect. λ decays linearly from λ_max at the smallest slice to 1.0× at the full pipeline. Simulation uses held-out test-set predictions.</p>
</div></aside></section>
<section id="annex-focus-gain-sensitivity-across-λ-values" class="slide level2">
<h2>Annex: focus-gain sensitivity across λ values</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><img data-src="assets/sim_focus_gain_sweep_static.png" style="width:100.0%"></p>
</div><div class="column" style="width:42%;">
<ul>
<li>Each curve shows the <strong>net revenue delta in USD</strong> vs.&nbsp;the full-pipeline baseline for a given λ_max — dropped deals are simply unworked (zero revenue from them), so the only gain is the focus uplift on worked deals.</li>
<li>λ decays linearly to 1.0× at the full pipeline — so the gain is highest when the team is most concentrated.</li>
<li>Break-even shifts left as λ_max increases: under the static model, the base scenario breaks even at about <strong>top 28%</strong> of the ranked pipeline when <strong>λ_max = 2.0</strong>.</li>
<li>The current static deck uses <strong>λ_max = 2.00</strong> as the base scenario.</li>
</ul>
</div></div>
</section>
<section id="annex-strategic-lever-2-practical-contribution-formula" class="slide level2">
<h2>Annex: strategic lever 2 — practical contribution formula</h2>
<div class="smaller">
<p>We replace the old <code>revenue − rep cost</code> shortcut with a more realistic contribution measure:</p>
<p><code>Contribution = RealizedRevenue × margin_pct − SalesEffortCost − CommissionCost − AcquisitionCost − ServingCost</code></p>
<ul>
<li><strong>Realized revenue</strong>: <code>amount_i</code> if won, else <code>0</code></li>
<li><strong>Margin %</strong>: product-group proxy used as a COGS fallback
<ul>
<li>Car Accessories <code>68%</code>, Performance &amp; Non-auto <code>62%</code>, Tires &amp; Wheels <code>55%</code>, Car Electronics <code>58%</code>, default <code>63%</code></li>
</ul></li>
<li><strong>Sales effort cost</strong>: team base+overhead allocated from rep capacity</li>
<li><strong>Commission cost</strong>: <code>7%</code> of realized revenue</li>
<li><strong>Acquisition cost</strong>: route-to-market proxy
<ul>
<li>Fields Sales <code>2.4k</code>, Reseller <code>1.6k</code>, Telesales <code>0.85k</code>, Telecoverage <code>0.65k</code>, Other/default lower values</li>
</ul></li>
<li><strong>Serving cost</strong>: <code>8%</code> of realized won amount</li>
</ul>
<p>Why this matters: it keeps the earlier sales-effort framing, but separates fixed sales coverage from variable selling cost more cleanly, so the staffing curve is closer to how a B2B auto-parts sales team actually earns margin.</p>
</div>
</section>
<section id="annex-strategic-lever-2-reduce-the-salesforce-and-let-the-model-pick-the-best-opportunities" class="slide level2">
<h2>Annex: Strategic lever 2: Reduce the salesforce and let the model pick the best opportunities</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><img data-src="assets/sim_salesforce_reduction_main_static.png" style="width:100.0%"></p>
</div><div class="column" style="width:45%;">
<ul>
<li>Baseline: <strong>228 reps</strong>, <strong>$385M</strong> realized revenue, and about <strong>$121M</strong> contribution after margin, base+overhead, commission, acquisition, and serving costs.</li>
<li>Model ranks all opportunities by EV; each rep cut drops the lowest-ranked batch they covered.</li>
<li><strong>Optimal headcount: 221 reps</strong> → <strong>$384M</strong> revenue retained (99.7%) and <strong>+$1.2M</strong> contribution vs.&nbsp;baseline.</li>
<li>Last individually positive rep batch is around <strong>rep #221</strong> — beyond that, incremental contribution no longer covers incremental operating cost.</li>
</ul>
</div></div>

<aside><div>
<p>Headcount model assumes 100 opps/rep/period. Contribution uses product-margin proxies, <strong>$135K base+overhead per rep</strong>, <strong>7% commission on realized revenue</strong>, route-based acquisition-cost proxies, and an 8% serving-cost proxy. Simulation uses held-out test-set predictions.</p>
</div></aside></section>
<section id="annex-salesforce-reduction-marginal-contribution-per-rep-batch" class="slide level2">
<h2>Annex: salesforce reduction — marginal contribution per rep batch</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><img data-src="assets/sim_salesforce_reduction_marginal_static.png" style="width:100.0%"></p>
</div><div class="column" style="width:42%;">
<ul>
<li>Each bar shows the <strong>marginal contribution</strong> contributed by a batch of ~12 reps (one 100-opp increment), sorted from highest- to lowest-value batch.</li>
<li>The comparison line represents the <strong>incremental operating cost</strong> of the same batch, not a flat rep-cost shortcut.</li>
<li><strong>Blue bars</strong> are ROI-positive: the batch adds more contribution than cost. <strong>Red bars</strong> are ROI-negative: cutting those reps improves contribution margin.</li>
<li>Under the static ranking, the crossover is still late in the curve, which is why the contribution upside from resizing remains modest.</li>
</ul>
</div></div>
</section>
<section id="annex-binning-methods-easy-explanation" class="slide level2">
<h2>Annex: binning methods — easy explanation</h2>
<div class="smaller">
<ul>
<li><strong>Binning</strong> means replacing a raw variable with a small number of ranges.</li>
<li>Instead of using exact values like <code>17 days</code>, <code>43 days</code>, <code>91 days</code>, the model can work with bands like:
<ul>
<li><strong>0–30 days</strong></li>
<li><strong>31–60 days</strong></li>
<li><strong>60+ days</strong></li>
</ul></li>
<li>This is useful when the signal comes from <strong>thresholds</strong> or <strong>zones</strong>, not from a perfectly smooth linear relationship.</li>
<li>In practice, binning helps when variables are:
<ul>
<li>noisy</li>
<li>skewed</li>
<li>sensitive to outliers</li>
<li>easier to interpret in ranges than in raw units</li>
</ul></li>
<li>So the intuition is simple: <strong>group similar values together before modeling</strong>.</li>
</ul>
</div>
</section>
<section id="annex-binning-methods-what-optbinning-does" class="slide level2">
<h2>Annex: binning methods — what <code>optbinning</code> does</h2>
<div class="smaller">
<ul>
<li>This project uses <strong>supervised binning</strong> with <code>optbinning</code>.</li>
<li>“Supervised” means the bins are not chosen arbitrarily: they are learned using the <strong>target</strong>.</li>
<li>The algorithm searches for cut points that make the bins as different as possible with respect to the prediction target.</li>
<li>For classification, that means finding intervals where the <strong>win/loss mix</strong> is clearly different.</li>
<li>For regression-style use, it means finding intervals that better separate the <strong>amount behavior</strong>.</li>
<li>Compared with manual bucketing or equal-width bins, <code>optbinning</code> is trying to find <strong>more informative splits</strong>.</li>
<li>In this repo, the wrapper is <code>NamedBinningProcess</code> in <code>notebooks/4_modelling/binning.py</code>, which keeps the output compatible with the sklearn pipelines used in the experiments.</li>
</ul>
</div>
</section>
<section id="annex-binning-methods-the-3-usage-modes-in-this-repo" class="slide level2">
<h2>Annex: binning methods — the 3 usage modes in this repo</h2>
<div class="smaller">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Usage mode</th>
<th>What the pipeline outputs</th>
<th>Why use it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>bin</code></td>
<td>The learned bin labels themselves</td>
<td>Mainly useful for inspection / debugging / intermediate transforms</td>
</tr>
<tr class="even">
<td><code>bin_ohe</code></td>
<td>The learned bins, then one-hot encoded into dummy columns</td>
<td>Keeps non-linear threshold effects while staying interpretable in linear/logistic models</td>
</tr>
<tr class="odd">
<td><code>woe</code></td>
<td>One WoE value per binned variable</td>
<td>Compresses each variable into a single monotonic signal and often stabilizes logistic-type models</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Selected classifier in the main deck:</strong> <code>random_forest_classifier_balanced_calibrated</code></li>
<li>So the binning modes below describe the <strong>logit-family alternatives</strong> and supporting model variants, not the final chosen forest.
<ul>
<li>supervised bins are learned first</li>
<li>then the bins are one-hot encoded</li>
<li>then logistic regression is fit</li>
<li>then probabilities are calibrated</li>
</ul></li>
<li><strong>WoE pipelines</strong> in the annex leaderboard use the same supervised binning step, but replace each bin with its <strong>Weight of Evidence</strong> value instead of a set of dummy columns.</li>
<li><strong>WoE intuition:</strong> positive WoE = more win-heavy than average; negative WoE = more loss-heavy than average.</li>
</ul>
</div>
</section>
<section id="annex-how-to-read-iv-charts-classification-win-loss" class="slide level2">
<h2>Annex: how to read IV charts — classification / win-loss</h2>
<div class="smaller">
<ul>
<li><strong>Information Value (IV)</strong> is a score used to rank how much predictive signal a variable carries against a target.</li>
<li>For the <strong>classification / win-loss</strong> chart, IV is the classic binary-target version derived from <strong>Weight of Evidence (WoE)</strong>.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>IV range</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt; 0.02</td>
<td>Useless</td>
</tr>
<tr class="even">
<td>0.02 to 0.10</td>
<td>Weak</td>
</tr>
<tr class="odd">
<td>0.10 to 0.30</td>
<td>Medium</td>
</tr>
<tr class="even">
<td>0.30 to 0.50</td>
<td>Strong</td>
</tr>
<tr class="odd">
<td>&gt; 0.50</td>
<td>Suspiciously high → check for leakage</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Colors</strong> add direction, because IV itself is only a strength score:
<ul>
<li><strong>green</strong> = increasing relationship</li>
<li><strong>red</strong> = decreasing relationship</li>
<li><strong>gray</strong> = categorical or unclear direction</li>
</ul></li>
<li><strong>Asterisk (<code>*</code>)</strong> = strictly monotonic relationship across bins.</li>
<li>Very high IV values for process variables can reflect genuinely strong signal, but they should always be checked for <strong>timing leakage</strong>.</li>
</ul>
</div>
</section>
<section id="annex-how-to-read-iv-charts-regression-amount" class="slide level2">
<h2>Annex: how to read IV charts — regression / amount</h2>
<div class="smaller">
<ul>
<li>The <strong>regression / amount</strong> chart does <strong>not</strong> use the same IV definition as the win/loss chart.</li>
<li>It comes from <code>ContinuousOptimalBinning</code>, where IV is a <strong>surrogate separation metric based on differences in bin means</strong>.</li>
<li>So the regression IV values are useful for <strong>relative ranking within that chart</strong>, but they should <strong>not</strong> be read with the binary-IV table and should <strong>not</strong> be compared numerically to the classification IV values.</li>
<li>Practical reading rule:
<ul>
<li>use the <strong>classification IV chart</strong> with the standard heuristic bands</li>
<li>use the <strong>regression IV chart</strong> only to see which variables separate amount behavior the most within that chart</li>
</ul></li>
<li>This is why regression IV values can look numerically much larger: they are on a <strong>different scale</strong>, not evidence of impossible predictive power.</li>
</ul>
</div>
</section>
<section id="annex-original-text-version-of-the-modelling-use-cases-slide" class="slide level2">
<h2>Annex: original text version of the modelling use-cases slide</h2>
<div class="columns">
<div class="column" style="width:52%;">
<h3 id="selected-for-this-project">Selected for this project</h3>
<ul>
<li><strong>Process prioritization</strong>: rank opportunities by win propensity and support decisions on where sales effort should focus first.</li>
<li><strong>Opportunity sizing &amp; forecasting</strong>: estimate deal value and aggregate expected sales for planning, prioritization, and budget visibility.</li>
</ul>
</div><div class="column" style="width:48%;">
<h3 id="additional-opportunities-identified-in-the-data">Additional opportunities identified in the data</h3>
<ul>
<li><strong>Channel optimization</strong>: test what-if scenarios around route-to-market and engagement model choices.</li>
<li><strong>Secondary market segmentation</strong>: create actionable commercial segments from predicted value and conversion potential.</li>
<li><strong>Early warning systems</strong>: flag opportunities that are likely to deteriorate or stall.</li>
<li><strong>Budget allocation</strong>: guide sales effort and product-focus decisions across segments, regions, and product lines.</li>
</ul>
</div></div>
</section>
<section id="annex-original-text-version-of-the-crm-embedding-slide" class="slide level2">
<h2>Annex: original text version of the CRM embedding slide</h2>
<div class="columns">
<div class="column" style="width:52%;">
<h3 id="operational-flow">Operational flow</h3>
<p><strong>Opportunity created</strong> → <strong>score + expected value generated</strong></p>
<ul>
<li>As soon as a new opportunity enters the CRM, the workflow generates:
<ul>
<li><strong>win-propensity score</strong></li>
<li><strong>predicted amount</strong></li>
<li><strong>expected value = E[Amount] × P(Win)</strong></li>
</ul></li>
</ul>
<h3 id="crm-displays">CRM displays</h3>
<ul>
<li><strong>Priority tier</strong>: Top 10%, Top 25%, Top 50%, etc.</li>
<li><strong>Suggested action</strong>: focus / monitor / deprioritize</li>
<li>This gives frontline teams a simple operating signal without exposing model internals.</li>
</ul>
</div><div class="column" style="width:48%;">
<h3 id="weekly-pipeline-reviews">Weekly pipeline reviews</h3>
<ul>
<li>Review only opportunities above agreed propensity or expected-value thresholds.</li>
<li>Use those cutoffs to focus rep attention, escalation, and follow-up.</li>
</ul>
<h3 id="management-view">Management view</h3>
<ul>
<li><strong>Directional forecast = sum of predicted values</strong> across the active pipeline.</li>
<li>Management can compare it by region, route to market, owner, or priority tier.</li>
</ul>
</div></div>
</section>
<section id="annex-original-text-version-of-the-next-steps-slide" class="slide level2">
<h2>Annex: original text version of the Next steps slide</h2>
<ul>
<li>Pilot deployment (4–6 weeks):
<ul>
<li>Embed prioritization scores into CRM workflows</li>
<li>Run A/B test vs.&nbsp;current sales process and measure lift in conversion and revenue</li>
</ul></li>
<li>Define operating model (after pilot early results):
<ul>
<li>Incorporate funnel/client segmentation into the process</li>
<li>Potentially include product-level segmentation if it makes sense.</li>
<li>Set clear thresholds and actions (e.g., top deciles = sales focus)</li>
<li>Align sales forces with incentives and pipeline reviews to make sure model outputs are used effectively</li>
</ul></li>
<li>Monitor performance (starting after deployment):
<ul>
<li>Track conversion lift, cycle time, and revenue per opportunity</li>
<li>Continuously recalibrate thresholds and retrain models</li>
</ul></li>
<li>Scale and integrate (after pilot success):
<ul>
<li>Extend to full pipeline and embed in forecasting cadence</li>
<li>Incorporate into commercial planning and resource allocation</li>
<li>Explore applying strategic levers such as pipeline optimization and salesforce adjustments based on model insights</li>
</ul></li>
</ul>
</section>
<section id="annex-classification-cv-leaderboard" class="slide level2">
<h2>Annex: classification CV leaderboard</h2>
<div style="font-size: 80%;">
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">ROC AUC</th>
<th style="text-align: right;">PR AUC</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>xgboost</td>
<td style="text-align: right;"><strong>92.9% ± 0.4%</strong></td>
<td style="text-align: right;"><strong>82.2% ± 0.5%</strong></td>
<td style="text-align: right;"><strong>88.3% ± 0.4%</strong></td>
<td style="text-align: right;"><strong>78.5% ± 0.9%</strong></td>
<td style="text-align: right;">66.8% ± 1.2%</td>
<td style="text-align: right;">72.2% ± 0.9%</td>
</tr>
<tr class="even">
<td>xgboost_balanced</td>
<td style="text-align: right;">92.8% ± 0.4%</td>
<td style="text-align: right;">82.0% ± 0.6%</td>
<td style="text-align: right;">86.2% ± 0.6%</td>
<td style="text-align: right;">65.7% ± 1.3%</td>
<td style="text-align: right;"><strong>82.0% ± 0.5%</strong></td>
<td style="text-align: right;"><strong>72.9% ± 0.9%</strong></td>
</tr>
<tr class="odd">
<td>random_forest_classifier</td>
<td style="text-align: right;">91.4% ± 0.4%</td>
<td style="text-align: right;">77.3% ± 1.0%</td>
<td style="text-align: right;">84.7% ± 0.6%</td>
<td style="text-align: right;">62.6% ± 1.1%</td>
<td style="text-align: right;">80.9% ± 0.6%</td>
<td style="text-align: right;">70.6% ± 1.0%</td>
</tr>
<tr class="even">
<td>random_forest_classifier_balanced</td>
<td style="text-align: right;">91.4% ± 0.4%</td>
<td style="text-align: right;">77.3% ± 1.0%</td>
<td style="text-align: right;">84.7% ± 0.6%</td>
<td style="text-align: right;">62.6% ± 1.1%</td>
<td style="text-align: right;">80.9% ± 0.6%</td>
<td style="text-align: right;">70.6% ± 1.0%</td>
</tr>
<tr class="odd">
<td>random_forest_classifier_balanced_calibrated</td>
<td style="text-align: right;">91.2% ± 0.4%</td>
<td style="text-align: right;">76.7% ± 1.2%</td>
<td style="text-align: right;">86.9% ± 0.4%</td>
<td style="text-align: right;">73.2% ± 1.1%</td>
<td style="text-align: right;">66.6% ± 1.0%</td>
<td style="text-align: right;">69.8% ± 0.8%</td>
</tr>
<tr class="even">
<td>logit_elasticnet_binned_ohe_balanced</td>
<td style="text-align: right;">88.1% ± 0.4%</td>
<td style="text-align: right;">69.8% ± 0.5%</td>
<td style="text-align: right;">79.4% ± 0.8%</td>
<td style="text-align: right;">53.0% ± 1.2%</td>
<td style="text-align: right;">81.8% ± 0.8%</td>
<td style="text-align: right;">64.3% ± 1.1%</td>
</tr>
<tr class="odd">
<td>logit_binned_ohe_balanced</td>
<td style="text-align: right;">88.1% ± 0.4%</td>
<td style="text-align: right;">69.8% ± 0.5%</td>
<td style="text-align: right;">79.4% ± 0.8%</td>
<td style="text-align: right;">53.0% ± 1.1%</td>
<td style="text-align: right;">81.8% ± 0.8%</td>
<td style="text-align: right;">64.3% ± 1.0%</td>
</tr>
<tr class="even">
<td>logit_binned_ohe_balanced_calibrated</td>
<td style="text-align: right;">88.1% ± 0.4%</td>
<td style="text-align: right;">69.8% ± 0.5%</td>
<td style="text-align: right;">84.0% ± 0.3%</td>
<td style="text-align: right;">71.1% ± 0.7%</td>
<td style="text-align: right;">50.1% ± 1.2%</td>
<td style="text-align: right;">58.8% ± 1.0%</td>
</tr>
<tr class="odd">
<td>logit_binned_ohe</td>
<td style="text-align: right;">88.1% ± 0.4%</td>
<td style="text-align: right;">70.0% ± 0.5%</td>
<td style="text-align: right;">84.2% ± 0.3%</td>
<td style="text-align: right;">71.1% ± 0.9%</td>
<td style="text-align: right;">51.3% ± 1.3%</td>
<td style="text-align: right;">59.6% ± 1.1%</td>
</tr>
<tr class="even">
<td>logit_elasticnet_binned_ohe</td>
<td style="text-align: right;">88.1% ± 0.4%</td>
<td style="text-align: right;">70.0% ± 0.5%</td>
<td style="text-align: right;">84.2% ± 0.3%</td>
<td style="text-align: right;">71.3% ± 0.8%</td>
<td style="text-align: right;">51.0% ± 1.2%</td>
<td style="text-align: right;">59.4% ± 1.0%</td>
</tr>
<tr class="odd">
<td>logit_elastic_binned_woe_balanced</td>
<td style="text-align: right;">87.7% ± 0.4%</td>
<td style="text-align: right;">69.2% ± 0.3%</td>
<td style="text-align: right;">79.0% ± 0.6%</td>
<td style="text-align: right;">52.4% ± 0.9%</td>
<td style="text-align: right;">80.9% ± 0.6%</td>
<td style="text-align: right;">63.6% ± 0.7%</td>
</tr>
<tr class="even">
<td>logit_elastic_binned_woe</td>
<td style="text-align: right;">87.7% ± 0.4%</td>
<td style="text-align: right;">69.3% ± 0.4%</td>
<td style="text-align: right;">83.8% ± 0.2%</td>
<td style="text-align: right;">71.7% ± 0.9%</td>
<td style="text-align: right;">47.3% ± 1.1%</td>
<td style="text-align: right;">57.0% ± 0.9%</td>
</tr>
<tr class="odd">
<td>logit_binned_woe</td>
<td style="text-align: right;">87.7% ± 0.4%</td>
<td style="text-align: right;">69.3% ± 0.4%</td>
<td style="text-align: right;">83.8% ± 0.2%</td>
<td style="text-align: right;">71.8% ± 0.8%</td>
<td style="text-align: right;">47.3% ± 0.9%</td>
<td style="text-align: right;">57.0% ± 0.8%</td>
</tr>
<tr class="even">
<td>logit_elasticnet_robust_scaler_balanced</td>
<td style="text-align: right;">86.8% ± 0.6%</td>
<td style="text-align: right;">66.9% ± 1.1%</td>
<td style="text-align: right;">78.7% ± 0.7%</td>
<td style="text-align: right;">52.0% ± 1.0%</td>
<td style="text-align: right;">79.6% ± 1.1%</td>
<td style="text-align: right;">62.9% ± 1.1%</td>
</tr>
<tr class="odd">
<td>logit_elasticnet_robust_scaler</td>
<td style="text-align: right;">86.8% ± 0.6%</td>
<td style="text-align: right;">67.5% ± 1.1%</td>
<td style="text-align: right;">82.8% ± 0.2%</td>
<td style="text-align: right;">68.4% ± 0.6%</td>
<td style="text-align: right;">45.5% ± 1.1%</td>
<td style="text-align: right;">54.6% ± 0.8%</td>
</tr>
<tr class="even">
<td>classic_logit_robust_scaler</td>
<td style="text-align: right;">86.8% ± 0.6%</td>
<td style="text-align: right;">67.5% ± 1.1%</td>
<td style="text-align: right;">82.8% ± 0.2%</td>
<td style="text-align: right;">68.4% ± 0.6%</td>
<td style="text-align: right;">45.5% ± 1.1%</td>
<td style="text-align: right;">54.7% ± 0.8%</td>
</tr>
<tr class="odd">
<td>random_classifier</td>
<td style="text-align: right;">50.2% ± 0.2%</td>
<td style="text-align: right;">22.8% ± 0.1%</td>
<td style="text-align: right;">65.4% ± 0.1%</td>
<td style="text-align: right;">23.0% ± 0.3%</td>
<td style="text-align: right;">22.4% ± 0.3%</td>
<td style="text-align: right;">22.7% ± 0.3%</td>
</tr>
<tr class="even">
<td>always_true_classifier</td>
<td style="text-align: right;">50.0% ± 0.0%</td>
<td style="text-align: right;">22.7% ± 0.0%</td>
<td style="text-align: right;">22.7% ± 0.0%</td>
<td style="text-align: right;">22.7% ± 0.0%</td>
<td style="text-align: right;">100.0% ± 0.0%</td>
<td style="text-align: right;">37.0% ± 0.0%</td>
</tr>
</tbody>
</table>
<p>Selected model in main deck: <strong>random_forest_classifier_balanced_calibrated</strong>.</p>
</div>
</section>
<section id="annex-regression-cv-leaderboard" class="slide level2">
<h2>Annex: regression CV leaderboard</h2>
<div style="font-size: 80%;">
<table class="caption-top">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">R²</th>
<th style="text-align: right;">MAE (USD)</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">Median APE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>xgboost_boxcox</td>
<td style="text-align: right;">0.062 ± 0.010</td>
<td style="text-align: right;">65.1k ± 1.5k</td>
<td style="text-align: right;">164.1% ± 31.2%</td>
<td style="text-align: right;">61.7%</td>
</tr>
<tr class="even">
<td>xgboost_log1p</td>
<td style="text-align: right;">0.015 ± 0.009</td>
<td style="text-align: right;">65.9k ± 1.5k</td>
<td style="text-align: right;">131.3% ± 26.1%</td>
<td style="text-align: right;">61.8%</td>
</tr>
<tr class="odd">
<td>xgboost_yeojohnson</td>
<td style="text-align: right;">0.062 ± 0.010</td>
<td style="text-align: right;">65.1k ± 1.5k</td>
<td style="text-align: right;">165.2% ± 32.3%</td>
<td style="text-align: right;">61.8%</td>
</tr>
<tr class="even">
<td>linear_power_scaler_binned_ohe</td>
<td style="text-align: right;">0.043 ± 0.009</td>
<td style="text-align: right;">66.7k ± 1.4k</td>
<td style="text-align: right;">180.5% ± 37.7%</td>
<td style="text-align: right;">63.6%</td>
</tr>
<tr class="odd">
<td>classic_linear_yeojohnson_robust_scaler</td>
<td style="text-align: right;">0.041 ± 0.007</td>
<td style="text-align: right;">66.8k ± 1.4k</td>
<td style="text-align: right;">176.1% ± 34.3%</td>
<td style="text-align: right;">63.8%</td>
</tr>
<tr class="even">
<td>classic_linear_boxcox_robust_scaler</td>
<td style="text-align: right;">0.041 ± 0.007</td>
<td style="text-align: right;">66.8k ± 1.4k</td>
<td style="text-align: right;">176.2% ± 34.3%</td>
<td style="text-align: right;">63.9%</td>
</tr>
<tr class="odd">
<td>classic_linear_log1p_robust_scaler</td>
<td style="text-align: right;">-0.006 ± 0.006</td>
<td style="text-align: right;">67.7k ± 1.5k</td>
<td style="text-align: right;">148.3% ± 30.7%</td>
<td style="text-align: right;">64.1%</td>
</tr>
<tr class="even">
<td>median_regressor</td>
<td style="text-align: right;">-0.108 ± 0.002</td>
<td style="text-align: right;">75.0k ± 1.5k</td>
<td style="text-align: right;">124.7% ± 28.4%</td>
<td style="text-align: right;">74.6%</td>
</tr>
<tr class="odd">
<td>random_forest_regressor</td>
<td style="text-align: right;">0.147 ± 0.009</td>
<td style="text-align: right;">72.7k ± 0.9k</td>
<td style="text-align: right;">292.2% ± 65.4%</td>
<td style="text-align: right;">75.5%</td>
</tr>
<tr class="even">
<td>xgboost</td>
<td style="text-align: right;">0.156 ± 0.008</td>
<td style="text-align: right;">72.3k ± 0.9k</td>
<td style="text-align: right;">294.6% ± 54.5%</td>
<td style="text-align: right;">77.8%</td>
</tr>
<tr class="odd">
<td>xgboost_pseudohubererror</td>
<td style="text-align: right;">-0.477 ± 0.012</td>
<td style="text-align: right;">92.7k ± 1.5k</td>
<td style="text-align: right;">458.8% ± 94.4%</td>
<td style="text-align: right;">96.9%</td>
</tr>
<tr class="even">
<td>classic_linear_robust_scaler</td>
<td style="text-align: right;">0.134 ± 0.006</td>
<td style="text-align: right;">74.3k ± 1.1k</td>
<td style="text-align: right;">297.1% ± 54.9%</td>
<td style="text-align: right;">78.9%</td>
</tr>
<tr class="odd">
<td>linear_binned_ohe</td>
<td style="text-align: right;">0.134 ± 0.007</td>
<td style="text-align: right;">74.3k ± 1.0k</td>
<td style="text-align: right;">300.4% ± 55.2%</td>
<td style="text-align: right;">78.9%</td>
</tr>
<tr class="even">
<td>elastic_binned_woe</td>
<td style="text-align: right;">0.131 ± 0.008</td>
<td style="text-align: right;">74.3k ± 1.1k</td>
<td style="text-align: right;">298.7% ± 58.7%</td>
<td style="text-align: right;">79.3%</td>
</tr>
<tr class="odd">
<td>linear_binned_woe_robust_scaler</td>
<td style="text-align: right;">0.131 ± 0.008</td>
<td style="text-align: right;">74.3k ± 1.1k</td>
<td style="text-align: right;">298.7% ± 58.7%</td>
<td style="text-align: right;">79.3%</td>
</tr>
<tr class="even">
<td>mean_regressor</td>
<td style="text-align: right;">-0.000 ± 0.000</td>
<td style="text-align: right;">84.9k ± 1.3k</td>
<td style="text-align: right;">235.0% ± 53.9%</td>
<td style="text-align: right;">88.3%</td>
</tr>
<tr class="odd">
<td>random_regressor</td>
<td style="text-align: right;">-1.053 ± 0.057</td>
<td style="text-align: right;">115.0k ± 2.1k</td>
<td style="text-align: right;">164.1% ± 65.3%</td>
<td style="text-align: right;">90.4%</td>
</tr>
<tr class="even">
<td>elasticnet_robust_scaler</td>
<td style="text-align: right;">0.066 ± 0.003</td>
<td style="text-align: right;">79.7k ± 1.3k</td>
<td style="text-align: right;">260.6% ± 58.1%</td>
<td style="text-align: right;">97.6%</td>
</tr>
</tbody>
</table>
<p>Selected model in main deck: <strong>xgboost_boxcox</strong> by CV Median APE, tie-broken by MAE.</p>
</div>
</section>
<section id="annex-hold-out-calibration-of-the-selected-classifier" class="slide level2">
<h2>Annex: hold-out calibration of the selected classifier</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><img data-src="assets/annex_calibration_comparison.png" style="width:100.0%"></p>
</div><div class="column" style="width:42%;">
<ul>
<li>This chart shows the <strong>selected classifier itself</strong> on the held-out set: <code>random_forest_classifier_balanced_calibrated</code>.</li>
<li>It compares the model’s mean predicted win probability to the observed win rate across quantile bins.</li>
<li>The closer the curve sits to the 45-degree reference, the more usable the probabilities are for thresholding and expected-value calculations.</li>
</ul>
</div></div>
</section>
<section id="annex-hold-out-classification-report-at-the-selected-models-optimal-threshold" class="slide level2">
<h2>Annex: hold-out classification report at the selected model’s optimal threshold</h2>
<div class="smallest">
<p>Threshold chosen on <strong>training out-of-fold predictions</strong> by maximizing <strong>F1</strong> for the selected model: <strong>37.8%</strong> predicted win probability.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Threshold</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Selected @ optimal threshold</td>
<td style="text-align: right;">37.8%</td>
<td style="text-align: right;">85.8%</td>
<td style="text-align: right;">66.8%</td>
<td style="text-align: right;">74.7%</td>
<td style="text-align: right;">70.5%</td>
</tr>
<tr class="even">
<td>Random classifier</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">65.1%</td>
<td style="text-align: right;">23.5%</td>
<td style="text-align: right;">23.6%</td>
<td style="text-align: right;">23.5%</td>
</tr>
<tr class="odd">
<td>Always false</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">77.3%</td>
<td style="text-align: right;">0.0%</td>
<td style="text-align: right;">0.0%</td>
<td style="text-align: right;">0.0%</td>
</tr>
<tr class="even">
<td>Always true</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">22.7%</td>
<td style="text-align: right;">22.7%</td>
<td style="text-align: right;">100.0%</td>
<td style="text-align: right;">37.0%</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">TN</th>
<th style="text-align: right;">FP</th>
<th style="text-align: right;">FN</th>
<th style="text-align: right;">TP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Selected @ optimal threshold</td>
<td style="text-align: right;">15,751</td>
<td style="text-align: right;">1,825</td>
<td style="text-align: right;">1,359</td>
<td style="text-align: right;">3,811</td>
</tr>
<tr class="even">
<td>Random classifier</td>
<td style="text-align: right;">13,597</td>
<td style="text-align: right;">3,979</td>
<td style="text-align: right;">3,951</td>
<td style="text-align: right;">1,219</td>
</tr>
<tr class="odd">
<td>Always false</td>
<td style="text-align: right;">17,576</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5,170</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>Always true</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">17,576</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5,170</td>
</tr>
</tbody>
</table>
<p>Diagnostic note: the threshold is selected on train-side OOF predictions, then evaluated once on the untouched hold-out set shown here.</p>
</div>
</section>
<section id="annex-regression-error-by-amount-bin-on-the-hold-out-set" class="slide level2">
<h2>Annex: regression error by amount bin on the hold-out set</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><img data-src="assets/annex_regression_error_bins.png" style="width:100.0%"></p>
</div><div class="column" style="width:42%;">
<ul>
<li>The comparison shows where model error changes most across deal-size bands, instead of averaging everything into one MAE figure.</li>
<li>The transformed XGBoost variants dominate the relative-error ranking, with <strong>XGBoost Box-Cox</strong> narrowly leading overall.</li>
<li>The main gain comes from reducing typical proportional error, while the largest opportunities still drive a gap between per-deal accuracy and total-portfolio forecasting.</li>
</ul>
</div></div>
</section>
<section id="annex-held-out-forecast-bias-of-the-selected-amount-model" class="slide level2">
<h2>Annex: held-out forecast bias of the selected amount model</h2>
<div class="columns">
<div class="column" style="width:56%;">
<p><img data-src="assets/annex_forecast_bias.png" style="width:100.0%"></p>
</div><div class="column" style="width:44%;">
<ul>
<li>The selected amount model under-forecasts the held-out portfolio: <strong>$1.31B predicted</strong> vs <strong>$2.14B actual</strong>.</li>
<li>That is a gap of about <strong>$830M</strong>, or roughly <strong>39% below</strong> the realized total on the test set.</li>
<li>This is why the main deck uses the amount model for <strong>directional sizing and ranking</strong>, not as a committed aggregate forecast without an explicit bias-correction layer.</li>
<li>The same hold-out evaluation still supports the model for per-opportunity ordering because <strong>MAE ≈ $65K</strong> and <strong>Median APE ≈ 61%</strong> are judged at deal level, not portfolio-total calibration.</li>
</ul>
</div></div>
</section>
<section id="annex-strategic-lever-1-focus-the-same-team-on-fewer-better-ranked-deals-1" class="slide level2">
<h2>Annex: strategic lever 1 — focus the same team on fewer, better-ranked deals</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><img data-src="assets/sim_focus_gain_main.png" style="width:88.0%"></p>
</div><div class="column" style="width:45%;">
<ul>
<li>Same salesforce, fewer deals — dropped opportunities go unworked.</li>
<li>Focus gain grows as the slice shrinks (λ_max = 2.0× at top slice → 1.0× at full pipeline).</li>
<li>Break-even at <strong>top ~12%</strong>; optimal at <strong>top ~42%</strong> → <strong>$566M</strong> (+$181M vs.&nbsp;baseline).</li>
</ul>
</div></div>

<aside><div>
<p>Focus-gain λ_max is a scenario assumption, not an empirically estimated causal effect. λ decays linearly from λ_max at the smallest slice to 1.0× at the full pipeline. Simulation uses held-out test-set predictions.</p>
</div></aside></section>
<section id="annex-focus-gain-sensitivity-across-λ-values-1" class="slide level2">
<h2>Annex: focus-gain sensitivity across λ values</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><img data-src="assets/sim_focus_gain_sweep.png" style="width:100.0%"></p>
</div><div class="column" style="width:42%;">
<ul>
<li>Each curve shows the <strong>net revenue delta in USD</strong> vs.&nbsp;the full-pipeline baseline for a given λ_max — dropped deals are simply unworked (zero revenue from them), so the only gain is the focus uplift on worked deals.</li>
<li>λ decays linearly to 1.0× at the full pipeline — so the gain is highest when the team is most concentrated.</li>
<li>Break-even shifts left as λ_max increases: with the rerun dynamic classifier, the base scenario breaks even at about <strong>top 12%</strong> of the ranked pipeline when <strong>λ_max = 2.0</strong>.</li>
<li>The current simulation uses <strong>λ_max = 2.00</strong> as the base scenario.</li>
</ul>
</div></div>
</section>
<section id="annex-strategic-lever-2-reduce-the-salesforce-and-let-the-model-pick-the-best-opportunities-1" class="slide level2">
<h2>Annex: Strategic lever 2: Reduce the salesforce and let the model pick the best opportunities</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><img data-src="assets/sim_salesforce_reduction_main.png" style="width:100.0%"></p>
</div><div class="column" style="width:45%;">
<ul>
<li>Baseline: <strong>228 reps</strong>, <strong>$385M</strong> realized revenue, and about <strong>$121M</strong> contribution after margin, base+overhead, commission, acquisition, and serving costs.</li>
<li>Model ranks all opportunities by EV; each rep cut drops the lowest-ranked batch they covered.</li>
<li><strong>Optimal headcount: 100 reps</strong> → <strong>$361M</strong> revenue retained (93.8%) and <strong>+$29.5M</strong> contribution vs.&nbsp;baseline.</li>
<li>Last individually positive rep batch is around <strong>rep #82</strong> — after that point, incremental contribution no longer covers incremental operating cost.</li>
</ul>
</div></div>

<aside><div>
<p>Same contribution formula as the static version, but applied to the stronger dynamic ranking. Simulation uses held-out test-set predictions.</p>
</div></aside></section>
<section id="annex-salesforce-reduction-marginal-contribution-per-rep-batch-1" class="slide level2">
<h2>Annex: salesforce reduction — marginal contribution per rep batch</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><img data-src="assets/sim_salesforce_reduction_marginal.png" style="width:100.0%"></p>
</div><div class="column" style="width:42%;">
<ul>
<li>Each bar shows the <strong>marginal contribution</strong> contributed by a batch of ~12 reps (one 100-opp increment), sorted from highest- to lowest-value batch.</li>
<li>The comparison line represents the <strong>incremental operating cost</strong> of the same batch.</li>
<li><strong>Blue bars</strong> are ROI-positive: the batch adds more contribution than cost. <strong>Red bars</strong> are ROI-negative: cutting those reps improves contribution margin.</li>
<li>With the stronger dynamic ranking, the crossover happens much earlier, around <strong>rep #82</strong>, which is why the resized team becomes much smaller under this richer formula.</li>
</ul>
</div></div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="assets/hero.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: false,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: false,

        // Push each slide change to the browser history
        history: false,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1920,

        height: 1080,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>